# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4cbc435bba01b8b127113449d46626b0fbaedaf26cf68ed5ac77a5e7927cc74f690f13e78f85e47ec78defbb1894bf8b1c75bba1bffc97aeba296ba6c5f405a

test:
  secret_key_base: a3b9493483505929d1d20e0a3cc1f9f2277c84e6f239093e2119e770e662c6f1d37125da02413c6c1c5b81304f3ebf68ab706d70d34b6ba192c5d69b687390c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
